### ISSUE TITLE
how to prepare canon.fa and decoy.fa for non-human organism?

### ISSUE THREAD

**Issue by qingyun-mei** [bioinformatics-centre/BayesTyper#22]
Hi, 
I can not prepare the canon.fa and decoy.fa for non-human organism, could you tell me how to do that?

**Comment by jonassibbesen** [comment]
Hi, 

The wiki contains a section on [Running BayesTyper on other organisms](https://github.com/bioinformatics-centre/BayesTyper/wiki/Running-BayesTyper-on-other-organisms). In there is a short description on what the decoy file should contain.

Let me know if this does not help.

Best,

Jonas

**Comment by qingyun-mei** [comment]
Hi，Jonas：
I combine vcf files of different samples use bayesTyperTools combine, it appeared errors as follows and the merged output file is empty. The vcf file was extracted by Assemblytic tools. Could you know how to avoid this error. Thanks very much!
[19/02/2020 22:00:41] Number of included alternative alleles (excluding id and missing):

	- Assemblytic: 0
	- Assemblytic: 0
	- Assemblytic: 0
	- Assemblytic: 0
	- Assemblytic: 0
	- Assemblytic: 0
	- Assemblytic: 0
	- Assemblytic: 0
	- Assemblytic: 0
	- Assemblytic: 0
	- Assemblytic: 0
	- Assemblytic: 0

[19/02/2020 22:00:41] Number of alternative alleles in the combined set: 0

Best regards!
mei
