### ISSUE TITLE
Assertion error when run bayesTyper cluster

### ISSUE THREAD

**Issue by qingyun-mei** [bioinformatics-centre/BayesTyper#23]
Hi, Jonas!
when I run bayesTyper cluster, it  appeared error as follows:

[20/02/2020 18:01:01] Parsing variants in unit 1 ...
bayesTyper: /opt/conda/conda-bld/bayestyper_1574250450004/work/src/bayesTyper/Chromosomes.cpp:145: bool Chromosomes::isDecoy(const string&) const: Assertion `order.find(name) != order.end()' failed.

Do you have ideas how to adjust it and make it run successfully!

Thanks

**Comment by qingyun-mei** [comment]
I have solved it ,thanks

**Comment by masen0407** [comment]
> I have solved it ,thanks



> I have solved it ,thanks
Hi,qingyun-mei !
i have the same bug and i don't konw how to fix it.
can you help me.

Thanks

**Comment by masen0407** [comment]
> I have solved it ,thanks
i have the same bug and i don't konw how to fix it.
can you help me.
how do you solve it?
