### ISSUE TITLE
Cram Support?

### ISSUE THREAD

**Issue by jjfarrell** [bioinformatics-centre/BayesTyper#24]
KMC3 presently does not read crams. Converting crams to a bam is an extra step that adds to the storage and CPU requirements. Is is there another kmer program that reads crams that could replace that step to generate the kmers needed for BayesTyper.

**Comment by jonassibbesen** [comment]
KMC is the only kmer counting tool that we currently support. My best suggestion is to make a feature request for CRAM support to the KMC developers. Sorry that I can not be of more help.

**Comment by jjfarrell** [comment]
Thanks for the response. I have put in a feature request for processing crams with KMC [https://github.com/refresh-bio/KMC/issues/141]) . It looks like it will take some time.  

Despite the necessary cram to bam conversion, it still is much faster than the other genotyper tools that I have tested.
