### ISSUE TITLE
Is BayesTyper suitable for non-human species?

### ISSUE THREAD

**Issue by songtaogui** [bioinformatics-centre/BayesTyper#3]
Dear BayesTyper developer,

I would like to do the SV genotyping using plant WGS data, I was wondering that Is BayesTyper suitable for non-human species ( for example, diploid plants )?

Thank you !

**Comment by lassemaretty** [comment]
Hi, 

Thank you for posting. BayesTyper can easily run on non-human species, however there are some details regarding the handling of the reference sequence (sex chromosomes in particular) that you should be aware of. We have written a [wiki](https://github.com/bioinformatics-centre/BayesTyper/wiki/Running-BayesTyper-on-non-human-data) with the details.

Please do not hesitate to post again if you have further questions. 

Br, 

Lasse

**Comment by songtaogui** [comment]
Dear Lasse,

Thank you for the kindly reply, and the detailed wiki helps. 

However, when trying the bayesTyper genotyping procedure, I met the error message below and exit when running KMC and bayesTyperTools makeBloom: 
```
$ kmc -fbam test.bam  test ./
**
Stage 1: 100%
Stage 2: 100%
1st stage: 0.826148s
2nd stage: 0.417656s
Total    : 1.2438s
Tmp size : 1MB

Stats:
   No. of k-mers below min. threshold :        29499
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :        53938
   No. of unique counted k-mers       :        24439
   Total no. of k-mers                :      1082156
   Total no. of reads                 :         9549
   Total no. of super-k-mers          :       138224

$ bayesTyperTools makeBloom -k test -p 1

[19/06/2018 21:32:48] You are using BayesTyperTools (v1.3.1)

[19/06/2018 21:32:48] Running BayesTyperTools (v1.3.1) makeBloom ...

bayesTyperTools: /isdata/kroghgrp/jasi/bayesTyper/code/releases/v1.3.1_static/BayesTyper/src/bayesTyperTools/MakeBloom.cpp:213: kmer_bloom_t* MakeBloom::kmc2bloomThreaded(const string&, float, uint): Assertion `kmc_table_info.kmer_length == kmer_size' failed.
Aborted (core dumped)
```

Do you have any idea what caused this failure ? 

Please find attached the bam files and the KMC3 out files .

Thank you!

[test.zip](https://github.com/bioinformatics-centre/BayesTyper/files/2115385/test.zip)

**Comment by lassemaretty** [comment]
Hi again, 

You need to inform KMC to count k-mers with k=55 (the default BayesTyper k-mer size). Try rerunning KMC with `-k55` added to the commandline.

I just realised that this information wasn't in the readme, Ive [updated](https://github.com/bioinformatics-centre/BayesTyper/blob/master/README.md#2-genotyping-based-on-variant-candidates) it now. Im sorry for the bother. 

br,

**Comment by songtaogui** [comment]
Thank you again. It finally works.

And I have another question irrelevant with this issue. I have learned that in your paper, the performance of BayesTyper and SVTyper were compared using both deletion and insertion classes of SVs. I have tried SVTyper (version: v0.6.0) and the default settings didn't support insertion calls. So could you please tell me that how did you call insertion genotype using SVTyper?

best wishes!

songtao gui

**Comment by jonassibbesen** [comment]
Dear Songtao,

Glad to hear that you got it to work. 

Yes, SVTyper does not support insertions (<INS>), however it supports duplications (<DUP>), which can also be classified as insertions. All insertions called by SVTyper in the paper are thus duplications.

Please let me know if you have any other questions.

Best wishes,

Jonas

**Comment by songtaogui** [comment]
Dear Jonas,

Thank you for the kindly reply. 

And I do have another question.

Does BayesTyper use split reads information during genotyping? Because I already have a batch of bam files aligned by bowtie2 (end-to-end), I was wondering is it OK if I use these bowtie2 bam during the BayesTyper Genotyping procedure, or do I have to realign with aligner such as BWA MEM to generate split reads information ？

Thank you for your help.

Best wishes,

Songtao Gui

**Comment by jonassibbesen** [comment]
Hi again,

BayesTyper does not use the read alignments for genotyping, but only the kmers counted from the read sequences. Therefore it is not important whether you have split read information or not. However, what is important, is that your bam files also contains the unmapped reads, since BayesTyper uses kmers from all reads including the unmapped. I have added a comment about the latter to the readme.

Having said that, if you are running the variant candidate generation step before genotyping, split reads are needed, since they are important for predicting larger structural variants. 

Let me know if you have any other questions.

Thank you for your interest in our method.

Best wishes,

Jonas

**Comment by songtaogui** [comment]
Dear Jonas & Lasse

Thank you for all your help. Glad to know that split read information is not important for genotyping.

So far I have no more questions and I will close this issue.

Thank you again for developing this wonderful genotyper!

Best wishes,

Songtaogui
