### ISSUE TITLE
byesTyper cluster wrong

### ISSUE THREAD

**Issue by masen1991** [bioinformatics-centre/BayesTyper#33]
i meet the same problem as https://github.com/bioinformatics-centre/BayesTyper/issues/23#issue-568178738
but i do not know how to handle it .
it like this :
Parsing variants in unit 2 ...
bayesTyper: /opt/conda/conda-bld/bayestyper_1574250450004/work/src/bayesTyper/Chromosomes.cpp:145: bool Chromosomes::isDecoy(const string&) const: Assertion `order.find(name) != order.end()' failed.
Aborted (core dumped)
i use BayesTyper (v1.5 )which install by conda.
My platform info:
Linux version 2.6.32-431.23.3.el6.x86_64 (mockbuild@x86-027.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Wed Jul 16 06:12:23 EDT 2014

conda 4.9.2

**Comment by jonassibbesen** [comment]
Hi,

This error is likely due to one of the reference sequences in either the vcf variant file or ploidy file (if that is used) not being present in the reference fasta files. 

Best,

Jonas

**Comment by masen1991** [comment]
Hello,@jonassibbesen
i run this:
byesTyper cluster -v samples.vcf.gz -s samples.tsv -g /bio/BayesTyper/bayes_37_38/bayestyper_GRCh38_bundle_v1.3/GRCh38_canon.fa -d /bio/BayesTyper/bayes_37_38/bayestyper_GRCh38_bundle_v1.3/GRCh38_decoy.fa -p 24

so i guess it maybe cause by my input vcf and samples.tsv  differ from bayestyper_GRCh38_bundle_v1.3/GRCh38_canon.fa or GRCh38_decoy.fa,so can i use my ref for the -d /-g ?or do i need to realignment my sample?
or maybe is there any scripts can rectify the difference from many kind of GRCh38 ref(with ALT or maybe chr prefix or chrM to chrMT),it all may cause bug and it really take a long time to find this bug.

**Comment by jonassibbesen** [comment]
Yes, you can use your own reference. We just provides the reference in the bundle to make it easier for some users. Here are our recommendations for what should be in the decoy:

*The decoy reference file should contain all chromosomes were the ploidy is unknown such as mitochondrial or unplaced contigs (unless they are known to be autosomal). Also remove all alternative contigs from both the genome and decoy reference file.*

Please let me know if you have any other problems.

**Comment by masen1991** [comment]
hello @jonassibbesen .
Thank you for this recommendations.
i try remove -d and use my ref in -g,it go well now .
hope it work
thank again
